name: Node.js tests and publication

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  elzii-tools:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./elzii-tools
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './elzii-tools/package-lock.json'
    - run: npm ci
    - run: npm run type-check
    - run: npm test -- --collectCoverage --coverageDirectory .
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: elzii-tools/coverage.xml
