name: Node.js tests and publication

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: { }

jobs:
  test-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: |
          ./elzii/package-lock.json
          ./elzii-tools/package-lock.json

    # library tests

    - run: npm ci
      working-directory: elzii      
    - run: npm run type-check
      working-directory: elzii
    - run: npm test -- --collectCoverage --coverageDirectory .
      working-directory: elzii

    # tooling tests

    - run: npm ci
      working-directory: elzii-tools
      
    - name: Install ANTLR4 tooling
      run: pipx install antlr4-tools
    - name: Generate ANTLR4 recognizers
      run: node scripts/antlrGen.mjs
      working-directory: elzii-tools
      
    - run: npm run type-check
      working-directory: elzii-tools
    - run: npm test -- --collectCoverage --coverageDirectory .
      working-directory: elzii-tools

    # merge and report
    
    - run: pipx install merge_cobertura
    - name: Merge coverage reports
      run: merge-cobertura elzii/coverage.xml elzii-tools/coverage.xml > merged.xml
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./merged.xml
